### ISSUE TITLE
Need help implementing

### ISSUE THREAD

**Issue by skearney6** [nazar-kuzo/azure-functions#1] opened 2023-01-16 14:44 UTC
I am having the same issue with Azure Functions authentication that you solved with this extension. I am looking forward to using it in my project, but I'm unclear how to implement your fix. What do I need to do once I have added the NuGet package to my project?

**Comment by nazar-kuzo** [comment] 2023-01-16 15:46
Hey @skearney6,

As it is described in a readme section you simply need:

1. Install NuGet package
2. Add/replace existing `AddAuthentication`/`AddAuthorization` extension methods to `AddFunctionAuthentication`/`AddFunctionAuthorization`

Optionally, if you want to use `[Authorize]` attributes with your Azure Functions you can install [DarkLoop.Azure.Functions.Authorize](https://www.nuget.org/packages/DarkLoop.Azure.Functions.Authorize) NuGet package

**Comment by skearney6** [comment] 2023-01-16 16:35
Thank you for the quick response!

That makes sense - I see what you're saying.

Once I tried that, I got this Function runtime error in the Azure portal when I deployed the function app:

`Microsoft.AspNetCore.Authentication.Abstractions: Scheme already exists: Bearer.`

Do you know why I would be getting this error? 

I feel like I must be missing something. It works when I run it locally, but when I deploy to Azure I get the error.

This is my Startup.cs:
```
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;
using Microsoft.Graph;
using Microsoft.Identity.Web;
using System.Reflection;

[assembly: FunctionsStartup(typeof(MyNamespace.Startup))]

namespace MyNamespace
{
    public class Startup : FunctionsStartup
    {
        public override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
        {
            // See https://stackoverflow.com/questions/57360238/using-configurationbuilder-in-functionsstartup
            FunctionsHostBuilderContext context = builder.GetContext();

            builder.ConfigurationBuilder
                .SetBasePath(context.ApplicationRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: false)
                .AddJsonFile($"appsettings.{context.EnvironmentName}.json", optional: true, reloadOnChange: false)
                .AddUserSecrets(Assembly.GetExecutingAssembly(), true, true)
                .AddEnvironmentVariables();
        }

        public override void Configure(IFunctionsHostBuilder builder)
        {
            var configAzureAd = builder.GetContext().Configuration.GetSection("AzureAd");

            builder.Services.AddFunctionAuthentication()
                .AddMicrosoftIdentityWebApi(configAzureAd)
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddMicrosoftGraphAppOnly(authenticationProvider => new GraphServiceClient(authenticationProvider))
                .AddInMemoryTokenCaches();
        }
    }
}
```

And my appsettings.json:
```
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "mydomain.onmicrosoft.com",
    "ClientId": "my-client-id",
    "TenantId": "my-tenant-id"
  }
}
```

**Comment by nazar-kuzo** [comment] 2023-01-16 16:40
@skearney6 Yes, I do recognize this error, it happens when AzureFunction Host crashes during Startup initialization and tries to restart. The root cause of it might be any exception during your Startup initialization. Try to catch this error by Remote debug or adding some try/catch and file logging etc.,

**Comment by nazar-kuzo** [comment] 2023-01-16 16:43
Ensure that your settings in Azure Function are complete according to the example, since I dont see you specified "ClientSecret" in your settings example

**Comment by skearney6** [comment] 2023-01-16 16:54
You're right - I should have mentioned that the ClientSecret value is in my user secrets locally and configured as an app setting in Azure. But it is there.

**Comment by skearney6** [comment] 2023-01-16 17:00
> @skearney6 Yes, I do recognize this error, it happens when AzureFunction Host crashes during Startup initialization and tries to restart. The root cause of it might be any exception during your Startup initialization. Try to catch this error by Remote debug or adding some try/catch and file logging etc.,

Thanks for the ideas, I will try to debug and see where it's erroring out.

**Comment by nazar-kuzo** [comment] 2023-01-24 11:12
@skearney6, How is it going?

I think I have answer for you. You get this error because you are using the conflicting scheme name "Bearer".

Under the hood this scheme name is used by Azure Function management to perform authorized actions.

Please try to run your setup with different scheme name like: "CustomBearer" or "B2B" etc., that should definitely help.

The reason why it works locally because AF host has disabled any built-in authentication locally.

I'll update the README file to avoid this confusion.

**Comment by Edward-Zhou** [comment] 2024-01-12 05:10
@nazar-kuzo Thanks for sharing this library. I am trying to achieve this. Does the custom scheme feature not include in package?
I installed the latest version `4.1.0`, it shows 
```
The best overload for 'AddFunctionAuthentication' does not have a parameter named 'defaultAuthenticationScheme'
```
If I use direct with below code:
```
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var config = builder.GetContext().Configuration;

            builder.Services.AddOptions<AzureAdOption>()
                .Configure<IConfiguration>((settings, configuration) =>
                {
                    configuration.GetSection("AzureAd").Bind(settings);
                });
            builder.Services.AddFunctionAuthentication()
                .AddMicrosoftIdentityWebApi(config, "AzureAd")
                .EnableTokenAcquisitionToCallDownstreamApi()
                .AddMicrosoftGraph(config.GetSection("DownstreamApi"))
                .AddInMemoryTokenCaches();
        }
```
It will throw below error
![image](https://github.com/nazar-kuzo/azure-functions/assets/16079555/619994bf-902e-4700-9ed9-dfd070342964)

@skearney6 Have you achieved making it working with Azure Function and Graph API?

**Comment by nazar-kuzo** [comment] 2024-01-12 10:45
@Edward-Zhou please download the main branch and look for the [AzureFunctions.Tests.Host](https://github.com/nazar-kuzo/azure-functions/tree/main/src/AzureFunctions.Tests.Host) project as an example.
The error you get is most likely caused by library versions mismatch, so you need to be very careful with nuget package versions you are using (on my experience I rarely run packages with latest version on Az Func in-proc model due to the same conflicts).

> Have you achieved making it working with Azure Function and Graph API?

I did, no problem running it at all, but Graph client package itself is bloated so I ended up using direct api calls with custom Http service, since big application size has impact on Az Func cold start times etc.

**Comment by nazar-kuzo** [comment] 2024-01-12 10:46
Closing since issue author is not responding with feedback

**Closed as not planned by nazar-kuzo** 2024-01-12 10:46 UTC
